[CI] Use `uv` for type-check (#222)
**TODO**: 
- [repo admin] After merge, remove required PR check `type-check (3.9)`
> error: The current Python platform is not compatible with the
lockfile's supported environments: `python_full_version >= '3.10'`

---------

Signed-off-by: Christian Kadner <ckadner@us.ibm.com>