Better Error Handling for attempts to run CB with pooling models (#476)
# Description

Using continuous batching with pooling models is not supported. But when
this opposing settings are used simultaneously the error is not so
clear.

Running with:
```bash
export VLLM_SPYRE_USE_CB=1
vllm serve BAAI/bge-reranker-large --no-enable-prefix-caching --max-model-len "512" --max-num-seqs "1" --tensor-parallel-size 1
```

Results in the following error:
```bash
 AttributeError: 'SpyrePoolingModelRunner' object has no attribute 'pre_warmup'
```

With this changes a warning is made and the variable automatically
changes to VLLM_SPYRE_USE_CB=0:
```bash
INFO 09-23 18:20:04 [spyre_worker.py:381] load model...
WARNING 09-23 18:20:04 [spyre_worker.py:388] Pooling models only support Static Batching. Using VLLM_SPYRE_USE_CB=0
INFO 09-23 18:20:10 [spyre_worker.py:409] load model took 5.997s
```

---------

Signed-off-by: Gabriel Marinho <gmarinho@ibm.com>
Signed-off-by: Max de Bayser <mbayser@br.ibm.com>
Co-authored-by: Max de Bayser <mbayser@br.ibm.com>